version: '3'

services:
  web:
    build: ./web # Build the web application Dockerfile
    ports:
      - "3000:3000" # Map the host port to the container port
    depends_on:
      - db # Depend on the db service

  db:
    build: ./db # Build the database Dockerfile