# Dockerfile für unsere DevOps Webapplikation

# Use the official Node.js image as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Expose the port on which the application will run
EXPOSE 3000

# Start a simple web server
CMD ["npx", "http-server", "-g", "-p", "3000"]